### ISSUE TITLE
Remove ML Flow dependency

### ISSUE THREAD

**Issue by pgarrison** [AllenCell/benchmarking_representations#18]
We should not expect external users to run mlflow.
* Use CSV logger by default in all experiments
* Instructions should not have steps that require mlflow

**Comment by fatwir** [comment]
This has been closed with this PR (https://github.com/AllenCell/benchmarking_representations/pull/31)

**Comment by fatwir** [comment]
I have not explicitly deleted the logger in the loggers folder (I have retained this there) - let me know if I need to remove this (I have however created a csv logger and replaced all the loggers in the log files to point to this csv logger)

**Comment by pgarrison** [comment]
Re-opening because the README still reference mlflow and Ritvik's work in #44 indicates that some experiments still use mlflow.
