### ISSUE TITLE
File path error for pcna notebook

### ISSUE THREAD

**Issue by fatwir** [AllenCell/benchmarking_representations#38]
For this notebook (https://github.com/AllenCell/benchmarking_representations/blob/main/src/br/notebooks/fig3_pcna.ipynb) to run, the references to the data in the pcna pointcloud folder does not include the new pcna_updated_sampling_morepoints subfolder in it (eg: a path such as ./morphology_appropriate_representation_learning/preprocessed_data/pcna/pointcloud/0015336b-e361-4ee7-bb73-e599be383d1e.ply will have to be renamed as ./morphology_appropriate_representation_learning/preprocessed_data/pcna/pointcloud/pcna_updated_sampling_morepoints/0015336b-e361-4ee7-bb73-e599be383d1e.ply) in the pcna manifest csv file!

**Comment by pgarrison** [comment]
This notebook has been replaced -- is this still relevant @fatwir?

**Comment by fatwir** [comment]
We can get rid of this. The scripts for the pcna dataset work as expected!
