### ISSUE TITLE
installation of dependencies for the preprocessing subdirectory

### ISSUE THREAD

**Issue by fatwir** [AllenCell/benchmarking_representations#52]
### Issue: Installation Failure from `pyproject.toml`

I was unable to install an environment from the `pyproject.toml` file located at:

```
/benchmarking_representations/subpackages/image_preprocessing
```

### Error Messages

During the installation process, I encountered the following errors:
 ```
[BuildError]: Cannot import 'pdm.backend'
  ```

### Workaround

For now, I have used a previously installed preprocessing environment (from [this](https://github.com/AllenCell/benchmarking_representations/tree/763d61b1a1788e06198a20a55663adc5c12cbec9) commit).

**Comment by pgarrison** [comment]
Can you share steps to reproduce the issue?

**Comment by pgarrison** [comment]
Drop the `--no-isolation`, this package doesn't need it, and doesn't include all the build dependencies in the main dependencies.

**Comment by fatwir** [comment]
Okay, this works...thanks!
